### ISSUE TITLE
Create pros and cons list of asking for LP, AB, DP and programme type information

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#119]
## Why?

We're split on how we want to ask for information that is often repeated for multiple ECTs or mentors.

## What?
We'd like to do a quick piece of analysis on the pros and cons of each of these approaches:

1. Asking for the information as a default initially (e.g. how it works in ECF1)
2. Asking for the information for the first time as you add an ECT, and then remembering that information

We should check if there are any other 'approaches' we're missing.

## Helpful links or other information
?

**Comment by claire-hughez** [comment]
Please review this, last comment in discussion here: https://github.com/DFE-Digital/ecf2/discussions/96

Just tagging folks that seemed interested in this default stuff, but anyone is welcome to review and leave feedback.
@JSJohal @mason-emily @kerry-b-dfe  @peteryates @tonyheadford @aabdi18

**Comment by peteryates** [comment]
Some unfiltered thoughts:

<dl>
  <dt>anything that blocks progress is a bad idea</dt>
  <dd>people have limited time and not being able to submit what they know and return for what they don't eats away at it</dd>

  <dt>asking for defaults makes subsequent registrations faster</dt>
  <dd>some things are already preselected, no need to filter a massive list repeatedly, probably really useful for big schools with lots of participants</dd>

  <dt>setting defaults needn't be a necessity</dt>
  <dd>if people can register ECTs and mentors fully without defaults we shouldn't stop them - making them aware it's a potential timesaver sounds like a good idea though</dd>

</dl>

**Comment by JSJohal** [comment]
Thanks @claire-hughez for compiling that list - looks good to me.

Only other thoughts I've got are:

- If we're taking the do less approach for MVP (and actually do the minimum), then it probably would be without having a designated journey to define 'defaults' when initially visiting the service. Or at least testing without that for starters...?
- Are we solutionising the idea of 'set your defaults at the start' because that's what we're used to? The need is around that users often have similar programme type information to add for their participants - what's the simplest way to test meeting that need?

**Comment by peteryates** [comment]
Again if we're starting from the minimum, maybe setting defaults needn't be mandatory, it just speeds things up for people who do set them?

**Comment by mason-emily** [comment]
- What if the first ECT added is doing something different to the rest of their ECTs?
- Would option 2 remember any previously selected choices or only the first / most recent one?

- Could we focus on programme & AB defaults for now and consider LP/DP when we look at partnership reporting since I think there may be different needs?

The multi add participants option that was mentioned before seems like a third option for meeting the need of speeding up the journey. I think both options 1 & 2 would be longer overall?

**Comment by claire-hughez** [comment]
Thanks for your thoughts everyone. Is there any particular reason people were leaving comments here rather than in the discussion? Might be easier to find later.

_anything that blocks progress is a bad idea_
I'm not sure I agree with that completely. What evidence is there for that? Is it useful to start registering someone before having key information in mind? Do we want data where they aren't certain of the kind of training the ECT is doing? (See Slack thread where I comment on this too!) Potentially, allowing people to give date and giving the impression they're done when they are not is actually more infuriating for the user and means we have to chase for more information.

I agree with the 2 other statements though @peteryates.

@JSJohal I agree with the second of those, but I would say given the current ECF1 has a way to 'set a default' in some sense, I'm keen to try and get something similar in MVP. I feel like otherwise we'd potentially add a lot of work to some users.

_What if the first ECT added is doing something different to the rest of their ECTs?_
You could have a checkbox asking if you want to remember that information. Seen this on other services before.

Not sure on Option 2 remembering several - but that would be an issue for both, no?

We looked at multi-add on Jas's doc and there seemed to be some key reasons not to do it, but happy to be challenged.

_Could we focus on programme & AB defaults for now and consider LP/DP when we look at partnership reporting since I think there may be different needs?_
I think it's hard to try and look at this for just certain fields, because I think it would make it a lot more confusing if users had to give these fields separately or in a different way when it would typically apply to all, or at least the majority, of  ECTs/mentors they register that year. We could wait to consider it more until after research or something else, but it feels better to give a stab testing something vaguely usable.

![Screenshot 2024-08-19 at 09 16 47](https://github.com/user-attachments/assets/c7bcfacd-bc5d-4e5d-9b60-c40e341916d0)

**Comment by gracecbrennan** [comment]
Next steps: we need to come to a decision on what we want to test. 

This analysis ticket can be closed.
