### ISSUE TITLE
Sprint 7 goals - Bulbasaur 🥬 - 5th to 16th of August

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#16]
# Sprint 7 - Bulbasaur

![Bulbasaur, a dual-type grass/poison Pokémon](https://github.com/user-attachments/assets/c26a1bc7-c629-4a50-b5ab-ccc25357d58a)

## Test and preparation objectives

Create and iterate prototypes to inform how we can improve the registration of ECTs and mentors for schools. 🏫

Test and iterate naming and separation of ECF digital services and terminology used within them. ✏️

 Prepare repositories, documentation and devvy stuff to prepare us to build 2.0. 🔨

Test with lead providers our ideas for solutions and get their feedback ☁️

Create success metrics for ECF 2.0 with the Data Insights team. 📊 

---

### Draft a journey for school registration 🏫 

*Interaction and content design* - Roughly prototype a low-fidelity and flexible registration journey for a school who has never registered before

*Business analysis* - Confirm what data is needed to be collected during initial registration for schools, for both mentors and ECTs

*Business analysis* - Work out requirements for initial registration of ECTs and mentors for schools and create a new service rules document to contain them

*Performance analysis* - Incorporate any relevant findings from web event data

*User research* - Discuss with design team any existing research we have to help inform this

### Create draft proposal for how services will be separated and named ✏ 

*Service design* - Proposal created and map to represent it 

*Content design* - Playback evidence gathered on names, naming session on away day and consider draft names to use until we can test 

*User research* - Discussion with content design to identify gaps in our understanding and what research we need to do around this

*Performance analysis* - Consider what data can be used to inform this work

### Decide how we're handling authentication and authorisation for user accounts 🔨 

*Team* - Meet with DFE sign in on how their roles and sub-services work

*Team* - Discuss and decide how authorisation will work for user accounts

*Interaction design* - Write design history on choosing to use DFE Sign in

### Plan the session for lead providers and complete analysis on completed research with lead providers to inform research we do in the future ☁ 

*Product* - Plan session based on feedback from lead providers

*User research* - Analyse existing user research on lead providers and inform what we need to do in future and connect with Nathan and other subject matter experts on what we might want to research

*Rest of team* - Input and feedback on slides and session for lead providers

### Set up support rotas and ways of working between 2.0 and the Schools team 🗒 

*Delivery* - Depends on progress on dev onboarding?

### Confirm success metrics after team awayday 📊 

*Performance analysis* - Investigate what data points can be tracked in ECF 1

*Product* - Confirm what success metrics we want to use for ECF 2 and how we could baseline with ECF 1

###  Onboard two developers to the team and start building _stuff_  🔨

*Development* - Continue to build and iterate the site for documentation

*Development* - Work through Tony and Pete's list of needed development tasks regardless if we focus on AB portal or ECF2 first

*Development* - Have conversations to onboard 2 new developers and consider creating a list of onboarding activities for any new developers that start later

**Comment by kas-madrigal** [comment]
Not sure if for this sprint (depending on how quick some of these tasks go) but could we consider creating

- Impact analysis/pre-mortem for user journey changes on users & other parts of the system i.e. grant funding & support team 
- impact analysis/pre-mortem of the 'rename and restructure of services' (thinking and comparing with wider CPD services as well as the golden thread, ITT, NPQ, etc) 
- I stopped [this task](https://lucid.app/lucidchart/33036c6e-b0f2-45d9-a6fb-a82c6b4e7de7/edit?viewport_loc=-707%2C-769%2C3596%2C1731%2C0_0&invitationId=inv_a449fb78-4784-40c8-80c0-b1b7e992f6b9) ([slack chat here](https://ukgovernmentdfe.slack.com/archives/C06V31R0Z17/p1721733198640529)) since I didn't think it was going to help the AB portal discussions we needed to have, but I do think it overlaps with some pieces of work we have going on now (user journey changes for example) 

Make sure you go through this piece of work https://lucid.app/lucidspark/5ec4dd85-c2e0-4370-816b-340f693ce272/edit?page=0_0# as it goes quite deeply into user journey for schools, Urvashi guided it
