### ISSUE TITLE
Decide how to handle when the appropriate body has already submitted induction data that is part of schools registration 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#348]
## Why?
In ECF2, we're going to consolidate the appropriate body portal from TRA into our database and set of services.

This means that in 1 database, we'll have:
1. Who the schools report the appropriate body is for a particular ECT
2. Appropriate bodies reporting that they are supporting a particular ECT's induction

Most of the time (we hope), this will be the same. The school will tell us Teaching School Hub 1 is supporting an ECT's induction, and the appropriate body will come and register that ECT with us.

However, we still need to think about how we hold that in our database and consider the information. Do we just store what schools put? Or what ABs put? Or both?

Mostly importantly, we know sometimes this might differ due to data mistakes. Anecdotally, it seems we should trust the appropriate body more than the school for the truth on who is supporting an ECT's induction. We know schools get confused with the terminology around different organisations that support ECT induction an training.

We also need to think about how we handle this when the AB reported differs from the school to the AB.

## What?
- Think about how we want to handle storing the appropriate body, given there may be 2 sources for this data
- Think about how we want to handle when the AB reported differs

## Out of scope
Actually prototyping or designing full solutions. For now, we just need a rough idea. For a while, the AB service will be live, and not the schools service.

**Comment by kas-madrigal** [comment]
From what I know @mason-emily @claire-hughez 

- User painpoint: schools get confused when selecting an AB on the manage training journey as they are only nominating it, not creating a real legal relationship with it. 
- After they have nominated, they sometimes want to change ABs (sometimes they are too expensive, there's another one closer to them...) and that's where _some_ of our disjointed data comes from. 

It would be good to do some quant analysis on the reasons for this data clash that aren't qual/anecdotal but alas if we don't have them I do think there is enough qual learning to put the weight of data validation on the AB. The real issue is how long it takes the AB to confirm this and the current service rules won't let the ECT start induction without AB confirming the relationship. In induction disco we suggested recording a provisional AB provided by the school that is then overridden by the AB confirmation so as not to stop the process of training and delay the induction in general.

**Comment by mason-emily** [comment]
I think this also applies for programme type which is reported by ABs too cc @emily-prudence-dfe

**Comment by claire-hughez** [comment]
It will also apply to induction start date. Would be good to consider all 3 if possible.

**Comment by claire-hughez** [comment]
https://educationgovuk.sharepoint.com/sites/TeacherServices/_layouts/15/doc.aspx?sourcedoc={ac32389e-06a8-4d1e-8f26-95defcdd0961}&action=edit

**Comment by claire-hughez** [comment]
This analysis is frying my brain.

I am adding to this:
- considering induction start date and school start date and the time period changes @tonyheadford  mentioned
- a new structure @mason-emily mentioned
- how we would handle differences in migrated ECF1 records

@mason-emily if you have time on Thurs and can just sense check the first section I wrote for:
_An appropriate body has claimed an ECT first, and then a school goes to register the same ECT_ 

That would be great. It's so fiddly and confusing!

**Comment by gracecbrennan** [comment]
Emily and Tony have reviewed. 

This is going over to Nathan now and we will have a review of how we're going to handle.

**Comment by gracecbrennan** [comment]
@claire-hughez has written tickets and shared to channel
