### ISSUE TITLE
Analyse Alerts & Prohibitions to inform rules for Claiming an ECT

### ISSUE THREAD

**Issue by emily-prudence-dfe** [DFE-Digital/register-early-career-teachers#516]
## Why?

We've been defining service rules relating to the Claim an ECT journey. One of the rules we're considering implementing is to prevent an ECT from being claimed if they are prohibited from teaching.

What we know about how inductions and alerts & prohibitions interact:

- There's no valid way for an ECT who is prohibited from teaching to start an induction.
- There's no validation check on the legacy AB portal which prevents ECTs who are prohibited from teaching from being registered on the service, but active alerts are shown on the ECT's record.
- We'd know if an ECT is prohibited from teaching by looking at the active alerts they have against them in TRS. Some alert types relate to prohibitions, while some don't. Not all alert types will be exposed via the TRS API.
- Appropriate Bodies are expected to verify that a school has undertaken pre-employment checks on an ECT before employing them in an induction post. This happens outside of the AB Portal.

## What?

- Document which which alerts in TRS are prohibitions from teaching, which are not prohibitions, and which will/won't be exposed via the TRS API.
- Define what this would look like as a service rule (e.g. If X alert types, then Y)
- Consider what this would look like for Training too - is there any reason why Training rules might be different to Induction?
- Work with Emily to make a recommendation on what we should implement in our MVP

## Out of scope

- Defining rules for bulk uploads
- Other claim rules e.g. exemptions

## Helpful links or other information

Phil Gallagher and John King are key contacts to help with this analysis.

**Comment by kas-madrigal** [comment]
Summary of catchup between Joe, Emily M, Emily P and Kas @joe-harrison-dfe 

We need to implement a rule preventing ECTs from being claimed if they have an alert but we need to know how to identify them and unpack what alert needs what kind of business rule. 

In ECF1 if someone has active alerts = true, they are blocked from being register and Colin needs to review it. This is a manual process. There are changes to the data used for this check. The API is changing which is why we can't use an active flag for the AB service as we have lost the Boolean indicator for someone's active alerts.  RECT can't use existing logic as they will not be using the same API. 

Would ECF2 need any different type of alerts for their systems? The participants with active flags is 2 in the last 18 months (Colin calculated) so the volume is very low. 

Next steps 
- Analysis on what alert types mean + categorising them. Only complication is things that aren't exposed via API (i.e. DBS alerts).
- Need to unpack what happens if an alert comes up after someone has been claimed? We don't know. We wouldn't have to check their API nightly to know that there was an alert added as TRA wanted to send an update to services using their API with the change but no decision has been made on what to do about it. It may be manual since volumes are so low.

**Comment by emily-prudence-dfe** [comment]
After speaking to @peteryates this morning on creating a system rule which blocks inductions being registered where an ECT is prohibited from teaching:

- If we have to implement any complex logic where **we** have to store a list of what to look for (e.g. our logic looks something like "If alert type A, B, or C then block ECT from being claimed, if alert type X, Y or Z then show alert on record) then this is complex to implement and upkeep; we'd have to store and maintain a list of alert types in our database which we'd have to update every time there is a change to alert types on TRS.

- If there is a simpler way to tell whether an ECT is prohibited from teaching - a yes/no prohibited field, or an indicator on an alert we could look for to tell us whether it's a prohibition or not _without_ having to store a list of alert types to help us with that logic, then it's less complex to implement.

- The simplest option would be to show an alert but not to block the journey. We have anecdotal evidence that on ECF1 (who don't block teachers with alerts from being registered, but do register and follow up manually) there are very low volumes of registrations where this is the case anyway. Could we look into this further to understand more?

**Comment by kas-madrigal** [comment]
@mason-emily maybe you could provide insight on what happens on ECF 1?

**Comment by joe-harrison-dfe** [comment]
Updates from speaking to Phil this morning on how we can use the alert types to create a rule blocking ABs from claiming an ECT who is prohibited from teaching:

- We can utilise the alert category instead of alert type to reduce the complexity of the logic. We would only block claiming an ECT for those with the alert category "Prohibition from Teaching"

- All other alert categories can be played back to the AB to highlight an alert but they would not be blocked from continuing.

- The API will hold all prohibition alerts apart from DBS barring which is a separate issue.

- There are roughly 150-200 teachers prohibited from teaching per year.

Next steps:

 - Further thinking needs to be done on what the process should be if a prohibition occurs during an ongoing induction. If this 
   happens TRS might be able to flag this to us and we can process it manually, but more analysis on this is required to determine 
   a service rule here.

**Comment by emily-prudence-dfe** [comment]
See https://github.com/DFE-Digital/register-early-career-teachers/issues/431 for discussion on this

**Comment by emily-prudence-dfe** [comment]
@joe-harrison-dfe do you think we could get a dev ticket written up on this today?

**Comment by gracecbrennan** [comment]
Joe has discussed with Phil - will write up dev ticket on this today

**Comment by gracecbrennan** [comment]
Dev ticket now complete. 

We can move this across to done.
