### ISSUE TITLE
Sprint 13 - Cubone 🦴 

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#520]
# Sprint 13

![Image](https://github.com/user-attachments/assets/f5f734f9-f1df-4b52-989f-2b255f9064b8)

---

### Finish testing and design new pages for adding ECT and adding mentors and build what we've already agreed is ready 🏫 

_Research_ - Finish sessions with schools on adding an ECT and mentor, analyse sessions and playback

_Design_ - Observe research and agree next steps from playback

_Design_ - Start designs for alternative pages for adding an ECT or mentor, when users are blocked from proceeding?

_Product_ - Agree if we ask schools for delivery partner

_Development_ - Build pages we've agreed are ready in the Add an ECT journey

_Analysis_ - How to handle appropriate body when it differs between what schools submit and appropriate bodies submit 

_Analysis/product_ - Plan how cut off dates will work based on teaching start date - will time periods be sorted otherwise?

_Analysis_ - Write up eligibility of mentors and write up any tickets for next steps

_Product_ - Plan sessions to share findings with lead providers and get their feedback

### Collect insights and complete analysis to inform designs to view ECT and mentor records, including statuses school users need to see 🏫 

_Analysis/design/product_ - Collect insights, problems and needs related to viewing ECT records

_Analysis/product_  - Analysis and discussion into statuses that should be considered for ECTs and mentors

_Performance analysis_ - Consider what we can analyse about the current pages to view ECTs and mentors in a list

### Create way to view records that are being migrated from ECF1 to Register ECTs and other data migration work 👾 

_Development_ - Build way to view records that are being migrated

### Finish building the Claim an ECT journey, so that it is ready to test with users 🛄 

_Development_ Build remaining unhappy paths (alerts and exemptions)

_Development_ Get staging environment ready for testing by non-developers

_Whole team_ Review the Claim journey and create a prioritised backlog of "best practice" updates (e.g. changes to content, missing buttons etc.)

### Build the first iteration of the Extensions user journey and record content, and confirm if updates to TRS are required 📏 

_Developent_ Build the Extensions user journey

_Development_ Add Extensions onto the View an ECT record

_Analysis_ Agree with TRA whether an update to TRS is required for extensions

### Understand how we will migrate Appropriate Body data into the new data model, and how this maps to DfE sign in data 🐦 

_Development_ Scope & test migration of AB data into the ECF2 data model

_Analysis_ Define how we identify and match Appropriate Body data to DfE sign-in records

### Complete user research round 1 with appropriate bodies, and continue engagement with them to set up for Round 2 🗣 

_Research_ Complete user research round 1 with appropriate bodies

_Research_ Agree high-level priorities for round 2 with appropriate bodies

_Product_ Agree launch date for the service and whether we will go out with comms with TRA Transformation

_Product_ Send comms to ABs with launch date

### Complete analysis & design on Release & Outcomes journeys, ready to build unhappy paths next sprint 🤔 

_Analysis_ Define a complete list of service rules for Release & Outcomes & populate backlog

_Design_ Create lo-fi designs for Release & Outcomes errors

### Create and agree admin console rules with TRA transformation 🖼 

_Design_ Define admin console rules for CPD, and a set of rules which dictate when updates should / shouldn't be possible in CPD or TRS console

_Development_ - Finish work to set up production environment monitoring

**Comment by kas-madrigal** [comment]
### Finish building the Claim an ECT journey, so that it is ready to test with users 🛄
- Development Build remaining unhappy paths (alerts (DONE) and exemptions & completion ticket (DONE)). #550 needs further defining. 
- Development Get staging environment ready for testing by non-developers. 
- Whole team Review the Claim journey and create a prioritised backlog of "best practice" updates (e.g. changes to content, missing buttons etc.) - #533 is in progress. We need to schedule this for a team call and we need to wait for Jack and Pete to finish the journey. 

### Build the first iteration of the Extensions user journey and record content, and confirm if updates to TRS are required 📏

- Developent Build the Extensions user journey - @emily-prudence-dfe has prepped for this ticket, 'ready to go' just needs finishing. Emily needs to chat to Pete about data model changes (there can be more than 1 extension and we need it recorded individually). 
- Development Add Extensions onto the View an ECT record. #557 
- Analysis Agree with TRA whether an update to TRS is required for extensions - no, they don't need an update. DONE. No ticket required. 

### Understand how we will migrate Appropriate Body data into the new data model, and how this maps to DfE sign in data 🐦

- Pete's goal - 'To continue writing and testing the import routine and get it to a point where it's robust enough to try running against real data in our sandbox environment.' 
- Development Scope & test migration of AB data into the ECF2 data model. No ticket so far, we need to write it, needs Pete input. 
- Analysis Define how we identify and match Appropriate Body data to DfE sign-in records. No ticket so far, we need to write it, needs Pete input. 

### Complete user research round 1 with appropriate bodies, and continue engagement with them to set up for Round 2 🗣
- Research Complete user research round 1 with appropriate bodies (DONE)
- Research Agree high-level priorities for round 2 with appropriate bodies. No ticket so far, needs ticket. 
- Product Agree launch date for the service and whether we will go out with comms with TRA Transformation. Blocked until TRA finish analysis round and migration of alerts. 
- Product Send comms to ABs with launch date. Blocked (See previous point). 

### Complete analysis & design on Release & Outcomes journeys, ready to build unhappy paths next sprint 🤔
- Analysis Define a complete list of service rules (how the thing works) for Release & Outcomes & populate backlog. Needs ticket. 
- Design Create lo-fi designs for Release & Outcomes errors. Needs ticket. 

### Create lo-fi designs for the admin console and agree admin console rules with TRA transformation 🖼
- Design Create lo-fi designs for the admin console. Needs ticket.
