### ISSUE TITLE
Get a view of the data that can't be migrated from ECF1 and decide next steps

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#611]
## Why?
When we migrate data from ECF1 to ECF2, we can see the data that is relatively clean and migrated correctly.

We need to get a better view of the messy records where they haven't migrated due to issues, so we can then categorise and attempt to fix these issues.

## What?
- Rework the migration failure information views so that we can show the actual failed records and related info to provide a better picture.
- Create follow up tickets to start to work out how to categorise and address these problems

**Comment by claire-hughez** [comment]
To check with Tony - is there a point where we should try and get more devs looped into this?

**Comment by tonyheadford** [comment]
> To check with Tony - is there a point where we should try and get more devs looped into this?

Yes definitely, I think once we've got a good view of what's happening then we'll need extra eyes/hands on:

1. Checking/updating/fixing the migrator logic
2. Adding new migrators and/or adding to the existing migrators as necessary to bring in extra data
3. Fixing ECF data so that we can migrate it
4. no doubt other stuff 🤔 

So I don't think in the next sprint of two as I'd like to get a much better view of the data first.

**Comment by gracecbrennan** [comment]
Ongoing - #828 is linked and being worked on

**Comment by tonyheadford** [comment]
Reopening as only sub-PR completed

**Comment by gracecbrennan** [comment]
Chipping away at this

**Comment by JSJohal** [comment]
Still some more to do this - picking up today
