### ISSUE TITLE
Confirm requirements for checking mentor eligibility

### ISSUE THREAD

**Issue by mason-emily** [DFE-Digital/register-early-career-teachers#620]
## Why?
As well as school eligibility requirements, there are eligibility requirements for participants to access training and funding. We need to confirm these eligibility requirements that the ECF 2 service needs to check.

## What?
- Confirm mentor eligibility requirements ECF 2 needs to cater for (and agree any that are out of scope for us)
- Agree when / how often we need to check / re-check eligibility

## Helpful links or other information
[Data we need to collect to fulfil our core purposes](https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=y01YD2y_B7-k&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6)

[ECT eligibility flow](https://lucid.app/lucidspark/b6f362cf-8201-4799-aac2-9efb0f18b2a9/edit?view_items=SbmazPBp09QE&invitationId=inv_cf2261a1-b288-46f7-bb47-51121c5d0ec6)

**Comment by gracecbrennan** [comment]
Will try to wrap this up today

**Comment by gracecbrennan** [comment]
still in progress

**Comment by mason-emily** [comment]
## Eligibility for mentoring
To be eligible for mentoring, a mentor should not have any prohibitions, sanctions or restrictions on their record.

(A mentor is also expected to hold QTS and have the necessary skills and knowledge to work successfully in this role - but this is for the school to determine and a mentor can be eligible without having QTS.)


## Eligibility for funded mentor training
Funded mentor training = funding to providers on receipt of submitted declarations

To be eligible for funded mentor training:

1. A mentor must be working at a school that is eligible for funding (see #125).

2. A mentor should not have any prohibitions, sanctions or restrictions on their record.

3. A mentor must be assigned to an ECT who is completing provider-led training. Note, the mentor does not have to stay paired with that ECT to be able to continue funded training.

4. A mentor must not have received funded ECF mentor training before. This means:
        - If a teacher completed mentor training as part of the Early Roll Out, they are not eligible for further funded training.
        - If a teacher has received a ‘Completed’ declaration for mentor training, they are not eligible for further funded training.
        - If a teacher started mentor training and 3 years have elapsed without completing the training, they are not eligible for further funded training (note, this is calculated as being eligible in 6 terms).

**Comment by easeynathan** [comment]
There's an additional requirement not stated here but possibly mentioned elsewhere: the requirement to possess a TRN i.e. if a mentor holds QTS then they will already have a TRN, but in those rare exceptions where a school appoints a mentor who does not hold QTS there is a chance that a mentor wouldn't have a TRN. Such mentors are still eligible for training but are required to apply to the TRA for a TRN in order to access funded training.

On eligibility criterion #2, the original policy steer was that only when a mentor had been barred from teaching would they also be deemed ineligible for funded training. I think most flags identified in the DQT/TRN don't meet that high bar. Or is this setting out a clarified position based on an updated policy steer? ECF1 does not re-check for this

On criterion #3, the eligibility for funded training commences when the mentor started mentoring the ECT, not from the date the mentor was assigned in the service. In ECF1, declarations submitted before eligibility is confirmed are ALL set to eligible at the point eligibility is confirmed which is not compliant. At the point criterion #3 is met, can the service only upgrade declarations to eligible if the declaration_date > start_date of the first mentorship period?

Re. criterion #4, the concept of re-checking eligibility is moot because the service needs to sometimes still recognise previous eligibility (to allow submission of back-dated declarations). ECF1 instead only captures that future training isn't allowed, via the separate `mentor_funding_end_date` attribute. This is not ideal. If Register can capture eligibility as time-sensitive rather than a stark boolean, it would require re-checking but those re-checks again would only affected continued/future eligibility and would not affect the previous period where the mentor was eligible.

**Comment by claire-hughez** [comment]
Emily has updated based on what Nathan has done. TBD on ITT scoping.
