### ISSUE TITLE
Find out more about how schools manage their responsibilities for ECF and induction

### ISSUE THREAD

**Issue by claire-hughez** [DFE-Digital/register-early-career-teachers#633]
## Why?
In our latest UR round, some schools stated they had a 'cheatsheet' from other organisations or that they compiled themselves to help them understand their responsibilities for induction and training of ECTs and mentors.

We want to understand more what the vital info is for schools, particularly when it comes to organisation beyond DFE.

We think talking to the strategic design team who have been looking into guidance for schools might help with this. They might have uncovered useful info in their latest UR round.

We also think that checking in with schools or sending a survey to get any files or useful info might help.

## What?
- Meet with Strategic design to find out about how they're handling guidance and school responsibilities
- Work out what else we might want to find out about and how

**Comment by claire-hughez** [comment]
Rosie will ask participants for their cheatsheets.

**Comment by claire-hughez** [comment]
Focusing on this today, will set meeting with Steve, and ask participants for docs

**Comment by rosalie-education** [comment]
Set up meeting with Stephen for Wednesday to hear about work to develop the 'information architecture' for the gov.uk guidance, and to discuss the cheat sheet insight. Asked participants to provide examples of the documents they were referring to. Strategic design shared [this relevant resource](https://educationgovuk.sharepoint.com/:p:/r/sites/TeacherServices/_layouts/15/Doc.aspx?sourcedoc=%7B9fde9c20-5bd2-4f36-b986-3c0a3fc866cd%7D&action=edit&wdPreviousSession=981dea67-0e46-df3d-2c34-a0c25deb162f) about challenges with comms

**Comment by claire-hughez** [comment]
Leonie is carrying out some UR with ABs, on their guidance. If they give SITs any cheatsheets or other documentation. She'll keep us updated.

**Comment by gracecbrennan** [comment]
No update until Rosie speaks with Stephen tomorrow.

**Comment by gracecbrennan** [comment]
Rosie to update ticket with results of conversations with SDT.

**Comment by rosalie-education** [comment]
Met with SDT on 20.11.24:

- Discussed work undertaken by SDT to prepare an information architecture ahead of designing new guidance;
- Shared the 'cheatsheet' insight, and highlighted some other UR findings (about participants not looking at drop-down toggles, participants stating they would leave the service and google what an AB is if they didn't know etc.); 
- Agreed to share prototype with SDT and Stephen in particular so that he can see the guidance that exists so far in the service; 
- Offered to share DG ahead of time to SDT (where timeframes and capacity allows) to let them review/input in areas of questioning where our team's priorities overlap 

Today I fed back the conversation to RECT team at stand up, and we agreed that:
- Doing bigger piece of research on this (i.e. a survey) is not a top priority for now / for MVP, but we can continue to ask specific comms-related questions in interviews; 
- We will keep the guidance in the toggles for now, but will revisit this later down the line (unless strong content recommendations to amend) and continue to observe/record participants interactions with these screens as research rounds progress.
